[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = ["*.js", "*.jsx", "*.ts", "*.tsx"]
excludes = ["*.json"]

[formatter.json]
command = "jsonfmt"
includes = ["*.json"]
excludes = ["home-manager/programs/neovim/nvim-pack-lock.json"]

[formatter.shell]
command = "shfmt"
options = ["-i", "2", "-s", "-w"]
includes = ["*.sh"]
