notify = [
  "bash",
  "-lc",
  "JSON=\"$1\"; LAST_MESSAGE=$(echo \"$JSON\" | jq -r '.\"last-assistant-message\" // \"Codex task completed\"'); osascript -e \"display notification \\\"$LAST_MESSAGE\\\" with title \\\"Codex\\\"\"",
  "notify",
]

[features]
undo = false
shell_tool = true
web_search_request = true
web_search_cached = true
unified_exec = true
apply_patch_freeform = true
exec_policy = true
experimental_windows_sandbox = false
elevated_windows_sandbox = false
remote_compaction = true
remote_models = true
shell_snapshot = true
child_agents_md = true
powershell_utf8 = false
enable_request_compression = false
collab = true
connectors = false
steer = true
collaboration_modes = true
responses_websockets = false

[model_providers.cliproxyapi]
name = "CLIProxyAPI"
base_url = "http://localhost:8317/v1"

[model_providers.lmstudio]
name = "LMStudio"
base_url = "http://127.0.0.1:1234/v1"

[model_providers.ollama]
name = "Ollama"
base_url = "http://127.0.0.1:11434/v1"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[profiles.gpt-oss-20b]
model = "gpt-oss:20b"
model_provider = "ollama"

[profiles.gpt-oss-120b]
model = "openai/gpt-oss-120b"
model_provider = "lmstudio"

[profiles.glm-4-7-flash]
model = "zai-org/glm-4.7-flash"
model_provider = "lmstudio"
